#!/usr/bin/env python3.7

import argparse
import logging

from comet.broker import Broker

DEFAULT_DUMP_PATH = "./"
DEFAULT_FILE_LOCK_TIME = 3600  # seconds
DEFAULT_PORT = 12050
LOG_FORMAT = "[%(asctime)s] %(name)s: %(message)s"

logging.basicConfig(format=LOG_FORMAT)


def str2bool(v):
    if v.lower() in ('yes', 'true', 't', 'y', '1'):
        return True
    elif v.lower() in ('no', 'false', 'f', 'n', '0'):
        return False
    else:
        raise argparse.ArgumentTypeError('Boolean value expected.')

def start(args):
    comet = Broker(args.dump_path, args.file_lock_time, args.debug, args.recover, args.port)
    comet.run_comet()


parser = argparse.ArgumentParser(description="This is comet (a Config and Metadata Tracker).")
parser.add_argument("-p", "--port", help="set port (default: {})".format(DEFAULT_PORT), default=DEFAULT_PORT, type=int)
parser.add_argument(
        "-d", "--dump-path",
        help="set dump path (default: '{}')".format(DEFAULT_DUMP_PATH),
        default=DEFAULT_DUMP_PATH
        )
parser.add_argument(
        "-t", "--file-lock-time",
        help="set file lock time in seconds (default: '{}')".format(DEFAULT_FILE_LOCK_TIME),
        default=DEFAULT_FILE_LOCK_TIME,
        type=int,
        )
parser.add_argument(
        "--debug",
        help="set debug mode (default: False)",
        default=False,
        type=str2bool,
        nargs='?',
        const=True,
        )
parser.add_argument(
        "--recover",
        help="set recover mode (default: True)",
        default=True,
        type=str2bool,
        nargs='?',
        const=True,
        )

parsed_args = parser.parse_args()

start(parsed_args)
exit(0)
