#!/usr/bin/env python3.7

import argparse
import logging

from comet.broker import Broker

DEFAULT_PORT = 12050
LOG_FORMAT = "[%(asctime)s] %(name)s: %(message)s"

#logging.basicConfig(format=LOG_FORMAT)


def str2bool(v):
    if v.lower() in ('yes', 'true', 't', 'y', '1'):
        return True
    elif v.lower() in ('no', 'false', 'f', 'n', '0'):
        return False
    else:
        raise argparse.ArgumentTypeError('Boolean value expected.')

def start(args):
    comet = Broker(**vars(args))
    comet.run_comet()


parser = argparse.ArgumentParser(description="This is comet (a Config and Metadata Tracker).")
parser.add_argument("-p", "--port", help="set port (default: {})".format(DEFAULT_PORT), default=DEFAULT_PORT, type=int)
parser.add_argument(
        "-t", "--file-lock-time",
        help="(deprecated) set file lock time in seconds",
        default=0,
        type=int,
        )
parser.add_argument(
        "--debug",
        help="set debug mode (default: False)",
        default=False,
        type=str2bool,
        nargs='?',
        const=True,
        )
parser.add_argument(
        "--recover",
        help="(deprecated: use redis-cli flushall if you really need to do that. You probably don't.) set recover mode",
        default=True,
        type=str2bool,
        nargs='?',
        const=True,
        )

parsed_args = parser.parse_args()

start(parsed_args)
exit(0)
